// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxlammhsylusuvpkfdsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bGFtbWhzeWx1c3V2cGtmZHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzEwNTYsImV4cCI6MjA2NTc0NzA1Nn0.uLNf3XTEzrGrg5iT0twnGlq51gIXQpslPMDxPKbDR7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);